[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { workspace = true }
bs58 = { workspace = true }
candid = { workspace = true }
hex = { workspace = true }
ic-cdk = { workspace = true }
ripemd ={ workspace = true }
serde = { workspace = true }
thiserror ={ workspace = true }
sha2 = { workspace = true }
